version: '3.7'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://database:27017/ChatGPT
  frontend:
    image: node:alpine
    working_dir: /app
    volumes:
      - './frontend:/app'
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend
  database:
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"